[package]
name = "cnvetti"
version = "0.1.0"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"]

[dependencies]
bio = "*"
rust-htslib = {git = "https://github.com/rust-bio/rust-htslib.git", branch = "master" }
clap = {version = "*", features = ["yaml", "color", "suggestions"]}
slog = "*"
slog-term = "*"
slog-async = "*"
chrono = "*"
shlex = "*"
separator = "*"
histogram = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
git-build-version = "*"
