[workspace]
members = [
    "cnvetti",
    "lib-coverage",
    "lib-debias",
    "lib-discover",
    "lib-filter",
    "lib-genotype",
    "lib-merge-cov",
    "lib-merge-seg",
    "lib-mod-cov",
    "lib-model-pool",
    "lib-model-wis",
    "lib-normalize",
]
