[package]
name = "lib-shared"
version = "0.1.0"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bihealth.de>"]

[dependencies]
bio = "*"
error-chain = "*"
regex = "*"
rust-htslib = { path = "../../rust-htslib" }
slog = {version = "*", features = ["max_level_trace", "release_max_level_debug"] }
